blank_issues_enabled: true
contact_links:
  - name: Code of Conduct
    url: https://github.com/ValMobile/RealisticSurvival-Wiki/blob/master/.github/CODE_OF_CONDUCT.md
    about: Please read this before posting
  - name: Discord Server
    url: https://discord.gg/mMt3f4usqK
    about: Feel free to join our discord server
