name: Resource Pack Creation

on:
  push:
    branches:
    - master
    paths:
    - 'src/**'

jobs:
  sync:

    name: Create Resource Pack
    runs-on: ubuntu-latest

    steps:
    - name: Checking out Repository
      uses: actions/checkout@v2
    - name: Zipping src
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r Pack.zip src
